### PR TITLE
patch for using pypdfium2

### PR DESCRIPTION
**Pull request by mara004**
pypdfium2 is not published yet, but when it's out, you could consider switching, as that's where regular updates are planned. If you are only using the PDFium API, pypdfium2 should be fully compatible with the original pypdfium.

### CODE REVIEW

**Comment by mara004** [comment]
I'm not sure, but maybe you could even merge parts of pdfbrain into upstream pypdfium2? Our support model code is in [`_helpers.py`](https://github.com/pypdfium2-team/pypdfium2/blob/main/src/pypdfium2/_helpers.py) if you want to take a look. I had already been thinking about adding document and page support classes...

**Comment by mara004** [comment]
PyPDFium2 is published now and released on PyPI.

**Comment by mara004** [comment]
@mkroutikov

**Comment by mkroutikov** [comment]
Switched to `pypdfium2` in a separate branch. Thank you for providing `pypdfium2`!

Re: merging pdfbrain into `pypdfium2`: I think its premature, as `pdfbrain` is still pretty much an experiment. I'd like to have a freedom to change API, and experiment with text extraction.

Closing this PR

**Comment by mara004** [comment]
Thanks!
A small suggestion: You can do `import pypdfium2._pypdfium as pdfium` so that you only get the ctypesgen bindings and no pypdfium2 support model code, to keep the namespace cleaner.

**Pull request closed without merging**
